all:
	gcc -Wall `pkg-config --cflags gtk+-2.0 gstreamer-0.10 gstreamer-interfaces-0.10` lecteur.c -o lecteur `pkg-config  --libs gtk+-2.0 gstreamer-0.10 gstreamer-interfaces-0.10`
clean:
	rm -rf *o hello

